[workspace]
resolver = "2"
members = ["crates/rmut-core", "crates/rmut-session", "crates/rmut-front", "crates/rmut", "crates/rmut-egui"]

[workspace.package]
version = "2.6.4"
edition = "2024"
license = "MIT"
repository = "https://github.com/jaroslavpachola/rmut"
readme = "README.md"

[workspace.dependencies]
rmut-core = { path = "crates/rmut-core", version = "2.6.4" }
rmut-session = { path = "crates/rmut-session", version = "2.6.4" }
rmut-front = { path = "crates/rmut-front", version = "2.6.4" }
anyhow = "1"
ratatui = "0.29"
egui_extras = { version = "0.36", default-features = false, features = ["image"] }
eframe = { version = "0.36", default-features = false, features = ["glow", "wayland", "x11", "default_fonts"] }
chrono = "0.4"
mailparse = "0.16"
regex-lite = "0.1"
rmpv = "1"
libc = "0.2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "logging", "tls12"] }
webpki-roots = "0.26"
